version: 2

models:
  - name: stg_playstore_apps
    description: "Staging model for Google Play Store apps"
    columns:
      - name: app_key
        description: "Surrogate key"
        data_tests:
          - not_null
          - unique
      - name: app_id
        data_tests:
          - not_null
      - name: app_name
        data_tests:
          - not_null
      - name: catalog_rating
        data_tests:
          - not_null

  - name: stg_playstore_reviews
    description: "Staging model for app reviews"
    columns:
      - name: review_key
        data_tests:
          - not_null
          - unique
      - name: review_id
        data_tests:
          - not_null
      - name: rating
        data_tests:
          - not_null
      - name: app_id
        data_tests:
          - not_null
          - relationships:
              to: ref('stg_playstore_apps')
              field: app_id
              arguments: {}
